from openai.lib._pydantic import to_strict_json_schema
from pydantic import BaseModel, Field, create_model
from typing import List, Literal


def create_emotion_topic_model():
    """
    EmotionTopicModel represents a model containing a list of dictionaries encapsulating topics, emotions, and explanations related to a given text.
    """

    class EmotionTopicItem(BaseModel):
        """
        EmotionTopicItem represents a single topic with its name and an optional explanation.
        """

        entity: str = Field(
            default="", description="The entity of the text in English if applicable."
        )
        topic: str = Field(..., description="The topic of the text in English.")
        emotion: Literal[
            "anger",
            "anticipation",
            "disgust",
            "fear",
            "joy",
            "sadness",
            "surprise",
            "trust",
        ] = Field(
            ..., description="The Plutchik emotion associated with the topic in English"
        )
        topic_explanation: str = Field(
            ..., description="Short explanation of why the topic was chosen in English."
        )
        emotion_explanation: str = Field(
            ...,
            description="Short explanation of why the emotion was chosen in English.",
        )

        class Config:
            extra = "forbid"  # Disallow additional properties

    fields = {
        "emotopic": (
            List[EmotionTopicItem],
            Field(
                ...,
                description="List of topics related to the text in English",
                max_items=5,
            ),
        ),
        "bot": (
            bool,
            Field(
                default=False,
                description="Indicates if the response was generated by a bot. Default is False.",
            ),
        ),
        "genai": (
            bool,
            Field(
                default=False,
                description="Indicates if the response was generated by a generative AI model. Default is False.",
            ),
        ),
    }

    EmoTopicGroup = create_model("TopicGroup", **fields)
    EmoTopicGroup.__doc__ = """
        EmotionTopicModel class representing a model containing a list of dictionaries encapsulating topics, emotions, and explanations related to a given text.
        The model is designed to handle a list of topics, each associated with a specific emotion from Plutchik's wheel of emotions.
        The model also includes flags to indicate if the response was generated by a bot or a generative AI model.
    """

    # Convert to strict schema
    schema = to_strict_json_schema(EmoTopicGroup)
    schema["additionalProperties"] = False
    if "$defs" in schema and "EmotionTopicItem" in schema["$defs"]:
        schema["$defs"]["EmotionTopicItem"]["additionalProperties"] = False

    return {
        key: schema[key]
        for key in [
            "additionalProperties",
            "$defs",
            "description",
            "properties",
            "title",
            "type",
            "required",
        ]
    }


def create_system_prompt(search_term: str) -> str:
    return f"""You are an advanced language model designed to analyze texts and extract structured information.

Context:
The text you will review are YouTube transcripts or comments on videos relating to the US tariff policy of 2025.
The search term used was {search_term}. This may not be directly related to the entity discussed in the text and should be used only as a reference for context.

Task:
Given a text, identify and extract the following details:

Entity – The entity of the text in English if applicable. If not applicable, it should be an empty string.
Topics – List the topics discussed in the text. Maximum number of topics is 5.
Emotions – For each topic, identify the emotions expressed (anger, anticipation, disgust, fear, joy, sadness, surprise, trust).
Topic Explanation – Concisely explain the reason behind the topic relating to the text. The explanations should be based on the text.
Emotion Explanation – Concisely explain the reason behind the emotion relating to the topic. The reasons should be based on the text, not inferred from the topic.

If topic has a neutral emotion, do not include it in the response.
"""
